/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "天涯若比邻",
  "description": "贾浅浅的屎尿体风格体诗真是太香了",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/assets/img/favicon.ico"
      }
    ]
  ],
  "pages": [
    {
      "title": "这是一个路由分支",
      "frontmatter": {},
      "regularPath": "/about/",
      "relativePath": "about/README.md",
      "key": "v-56aa5a5e",
      "path": "/about/",
      "headers": [
        {
          "level": 3,
          "title": "一级标题1",
          "slug": "一级标题1"
        },
        {
          "level": 3,
          "title": "一级标题1",
          "slug": "一级标题1-2"
        },
        {
          "level": 3,
          "title": "一级标题1",
          "slug": "一级标题1-3"
        },
        {
          "level": 3,
          "title": "一级标题1",
          "slug": "一级标题1-4"
        },
        {
          "level": 3,
          "title": "一级标题1",
          "slug": "一级标题1-5"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/hero.png",
        "heroText": "Hero 标题",
        "tagline": "Hero 副标题",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。",
            "footer": "MIT Licensed | Copyright © 2018-present Evan You"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-084c8d2d",
      "path": "/"
    }
  ],
  "themeConfig": {
    "lastUpdated": "Last Updated",
    "logo": "/assets/img/hero.png",
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "Guide",
        "link": "/about/"
      },
      {
        "text": "External",
        "link": "https://google.com"
      },
      {
        "text": "Languages",
        "ariaLabel": "Language Menu",
        "items": [
          {
            "text": "Chinese",
            "link": "/language/chinese/"
          },
          {
            "text": "Japanese",
            "link": "/language/japanese/"
          }
        ]
      }
    ],
    "sidebar": [
      {
        "title": "Group 1",
        "path": "/foo/",
        "collapsable": false,
        "sidebarDepth": 1,
        "children": [
          "/"
        ]
      },
      {
        "title": "Group 2",
        "children": [],
        "initialOpenGroupIndex": -1
      }
    ]
  }
}